//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.Service.Connector.CurrencyConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyConverterService.ICurrencyConverterService")]
    public interface ICurrencyConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyConverterService/GetCurrencyWordValue", ReplyAction="http://tempuri.org/ICurrencyConverterService/GetCurrencyWordValueResponse")]
        string GetCurrencyWordValue(decimal currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyConverterService/GetCurrencyWordValue", ReplyAction="http://tempuri.org/ICurrencyConverterService/GetCurrencyWordValueResponse")]
        System.Threading.Tasks.Task<string> GetCurrencyWordValueAsync(decimal currency);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyConverterServiceChannel : CurrencyConverter.Service.Connector.CurrencyConverterService.ICurrencyConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConverterServiceClient : System.ServiceModel.ClientBase<CurrencyConverter.Service.Connector.CurrencyConverterService.ICurrencyConverterService>, CurrencyConverter.Service.Connector.CurrencyConverterService.ICurrencyConverterService {
        
        public CurrencyConverterServiceClient() {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCurrencyWordValue(decimal currency) {
            return base.Channel.GetCurrencyWordValue(currency);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyWordValueAsync(decimal currency) {
            return base.Channel.GetCurrencyWordValueAsync(currency);
        }
    }
}
